### ISSUE TITLE
error trying to run the requirements

### ISSUE THREAD

**Issue by samuelhei** [bullsignals/binance-downloader#11]
Message from Bradley on Kaggle:

> 
> This didn't seem to work. I got an error trying to run the requirements:
> 
> Could not find a version that satisfies the requirement flit==0.13 (from -r requirements.txt (line 2)) (from versions: ) No matching distribution found for flit==0.13 (from -r requirements.txt (line 2))

**Comment by anderson89marques** [comment]
I uninstall all dependencies and I tried to install using requirements that worked fine.
Do you have more information about that problem?

**Comment by einewton** [comment]
> I updated my python to 3.6 and now it appears to be working as expected. Thank you!
