### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by einewton** [bullsignals/binance-downloader#13]
I wanted to get all of the data, so I set a very high limit, but when I do I get the following error:

0%|                                                                                 | 219500/99999999999999 [03:05<21402766:26:33, 1297.86it/s]
Traceback (most recent call last):
  File "\\kline-binance", line 4, in <module>
    main()
  File "\binance\cli.py", line 44, in main
    binance.consult(output)
  File "site-packages\binance\api.py", line 52, in consult
    self.kwargs['startTime'] = update_start_time(self.klines[-1].open_time)
IndexError: list index out of range

**Command Ran:**
kline-binance -i 1m -s XRPBTC -l 99999999999999 -st 01/01/2017 -e 05/04/2018

**Comment by santoshyadavdev** [comment]
Will start working on this issue.

**Comment by anderson89marques** [comment]
Nice. Thanks for your help @santoshyadav198613.

**Comment by samuelhei** [comment]
Closed on https://github.com/bullsignals/binance-downloader/pull/18
