### ISSUE TITLE
0%: download finished succesfully

### ISSUE THREAD

**Issue by kenorb** [bullsignals/binance-downloader#20]
The following command doesn't download anything:

```
$ kline-binance -i 1m -l 1000 -st 01/01/2016 -e 30/12/2016 -o ETHBTC-2016.csv
  0%|                                                                                                                                           | 0/1000 [00:00<?, ?it/s]All records downloaded for the provided date range.

download finished succesfully.
```

**Comment by anderson89marques** [comment]
Hi @kenorb,
For that period the API doesn't have data. 
Only 2017 and beyond have data.
I will investigate why the API has this limitation, but isn't our fault.
@samuelhei do you know something about that?

**Comment by samuelhei** [comment]
Maybe we need to show some message when there is no data, Binance is relative new exchange so is normal to not have old data.

@kenorb thanks for point that out.

**Comment by anson-vandoren** [comment]
Fixed. Below will now be response for similar requests (i.e., Binance does not have any data for given symbol, interval, and time range:

```console
⇒  kline-binance ETHBTC 1m --start 2016-01-01 --end 2016-12-30
[2018-12-29 22:17:14.714893] WARNING: binance_downloader.api: there are no k-lines for ETHBTC
at 1m intervals on Binance between 2016-01-01 00:00:00 and 2016-12-30 00:00:00
[2018-12-29 22:17:14.715162] WARNING: binance_downloader.api: Not writing to output file since no 
data was received from API
```
